#!/usr/bin/env bash
# Downloads @primer/octicons and regenerates the Octicons asset catalog folder
# plus the Swift catalog used by the icon picker.
# Usage: scripts/update-octicons.sh [version]
set -euo pipefail

VERSION="${1:-latest}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="$ROOT/GitHubBar/Resources/Assets.xcassets/Octicons"
CATALOG="$ROOT/GitHubBar/UI/Primer/OcticonCatalog.swift"

ICONS=(
  mark-github bell inbox mention eye person people organization repo
  git-pull-request git-pull-request-draft git-pull-request-closed git-merge
  issue-opened issue-closed code-review comment discussion-closed
  check check-circle x-circle alert stop skip dot-fill clock sync
  rocket zap flame bug beaker tools workflow play shield lock unlock
  star heart bookmark tag globe filter gear plus trash link-external
  milestone project-roadmap package dependabot copilot hubot
  git-commit git-branch versions history archive
  read unread bell-slash question download upload moon x
)

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
(cd "$TMP" && npm pack "@primer/octicons@$VERSION" --silent >/dev/null && tar xzf primer-octicons-*.tgz)
PKG_VERSION="$(node -p "require('$TMP/package/package.json').version")"

rm -rf "$ASSETS"
mkdir -p "$ASSETS"
cat > "$ASSETS/Contents.json" <<JSON
{
  "info" : { "author" : "xcode", "version" : 1 }
}
JSON

{
  echo "// Generated by scripts/update-octicons.sh from @primer/octicons $PKG_VERSION. Do not edit."
  echo
  echo "enum OcticonCatalog {"
  echo "    static let names: [String] = ["
} > "$CATALOG"

for name in "${ICONS[@]}"; do
  svg="$TMP/package/build/svg/$name-16.svg"
  if [[ ! -f "$svg" ]]; then
    echo "warning: $name-16.svg not found, skipping" >&2
    continue
  fi
  dir="$ASSETS/$name.imageset"
  mkdir -p "$dir"
  cp "$svg" "$dir/"
  cat > "$dir/Contents.json" <<JSON
{
  "images" : [ { "filename" : "$name-16.svg", "idiom" : "universal" } ],
  "info" : { "author" : "xcode", "version" : 1 },
  "properties" : {
    "preserves-vector-representation" : true,
    "template-rendering-intent" : "template"
  }
}
JSON
  echo "        \"$name\"," >> "$CATALOG"
done

{
  echo "    ]"
  echo "}"
} >> "$CATALOG"

echo "Octicons $PKG_VERSION -> $ASSETS"
